

String file1=
"<!DOCTYPE html>\r\n"
"<html lang='en'>\r\n"
"<head>\r\n"
"  <title>ESP8266 Relay Control v1.0</title>\r\n"
"  <meta charset='utf-8'>\r\n"
"  <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n"
"  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>\r\n"
"  <link href='https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css' rel='stylesheet'>\r\n"
"  <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>\r\n"
"  <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>\r\n"
"  <script src='https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js'></script>\r\n"
" </head>\r\n"
"<body>\r\n"
"<div class='container-fluid'>\r\n"
"  <div class='page-header text-cente'>\r\n"
"    <h1>ESP8266 Relay Control v1.0</h1>\r\n"
"  </div>\r\n"
"<div class='row form-group'>\r\n"
"  <div class='col-xs-12 col-sm-3 form-group'>\r\n"
"  <label class='checkbox-inline'>Relay 1&nbsp;&nbsp;</label>\r\n"
"  <input id='relay' name='relay1' type='checkbox'  data-toggle='toggle' onchange='relayAction(this,name)'></div>\r\n"
"  <div class='col-xs-12 col-sm-3 form-group'>\r\n"
"  <label class='checkbox-inline'>Relay 2&nbsp;&nbsp;</label>\r\n"
"  <input id='relay' name='relay2' type='checkbox'  data-toggle='toggle' onchange='relayAction(this,name)'></div>\r\n"
"  <div class='clearfix visible-xs'></div>\r\n"
"  <div class='col-xs-12 col-sm-3 form-group'>\r\n"
"  <label class='checkbox-inline'>Relay 3&nbsp;&nbsp;</label>\r\n"
"  <input id='relay' name='relay3' type='checkbox'  data-toggle='toggle' onchange='relayAction(this,name)'></div>\r\n"
"  <div class='col-xs-12 col-sm-3 form-group'>\r\n"
"  <label class='checkbox-inline'>Relay 4&nbsp;&nbsp;</label>\r\n"
"  <input id='relay' name='relay4' type='checkbox' checked data-toggle='toggle' onchange='relayAction(this,name)'></div>\r\n"
"</div>\r\n"
"</div>\r\n"
"<script>\r\n"
"  $(function() {\r\n"
"    $('#relay').bootstrapToggle();\r\n"
"  })\r\n"
"  \r\n"
"  function relayAction(el, name){\r\n"
"    if(el.checked){\r\n"
"      //console.log('on  - '+name);\r\n"
"      var url = '/'+name+'?state=on';\r\n"
"    }else{\r\n"
"      //console.log('off - '+name);\r\n"
"      var url = '/'+name+'?state=off';\r\n"
"    }\r\n"
"    //console.log(url);\r\n"
"    var xhReq = new XMLHttpRequest();\r\n"
"    xhReq.open('GET', url, true);\r\n"
"    xhReq.setRequestHeader('Content-type', 'application/json');\r\n"
"    xhReq.send();\r\n"
"    \r\n"
"    xhReq.onreadystatechange = function () {\r\n"
"      if (xhReq.readyState == 4 && xhReq.status == 200) {\r\n"
"        console.log(xhReq.responseText);\r\n"
"      }\r\n"
"    }\r\n"
"  }\r\n"
"</script>\r\n"
"</body>\r\n"
"</html>\r\n";

